import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  let prompt: string = '';
  
  try {
    const requestBody = await request.json();
    prompt = requestBody.prompt;

    // Validate input
    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Invalid prompt. Please provide a valid travel query.' },
        { status: 400 }
      );
    }

    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Mock trip plan response - this simulates what Ollama would return
    const mockTripPlan = {
      title: "Demo Trip Plan (Mock AI)",
      description: "This is a sample trip plan generated by the mock AI service while you set up Ollama. Once Ollama is installed, this will be replaced with real AI-generated content.",
      destination: "Delhi",
      from: "Your Location",
      duration: "1 day",
      estimatedBudget: "₹2,000 - ₹3,000",
      bestFor: "Solo/Couple",
      season: "October-March",
      itinerary: [
        {
          day: 1,
          title: "Exploring Delhi Highlights",
          description: "A perfect day covering Delhi's must-see attractions",
          activities: [
            {
              time: "09:00 AM",
              activity: "Visit Red Fort",
              description: "Start your day exploring this iconic Mughal fortress and UNESCO World Heritage site",
              location: "Red Fort, Chandni Chowk",
              estimatedCost: "₹50"
            },
            {
              time: "11:00 AM",
              activity: "Explore Chandni Chowk Market",
              description: "Walk through one of Delhi's oldest and busiest markets, famous for food and shopping",
              location: "Chandni Chowk",
              estimatedCost: "₹300"
            },
            {
              time: "01:00 PM",
              activity: "Lunch at Karim's",
              description: "Try authentic Mughlai cuisine at this legendary restaurant",
              location: "Karim's, Jama Masjid",
              estimatedCost: "₹500"
            },
            {
              time: "03:00 PM",
              activity: "Visit India Gate",
              description: "See the iconic war memorial and enjoy the surrounding gardens",
              location: "India Gate, Rajpath",
              estimatedCost: "₹0"
            },
            {
              time: "05:00 PM",
              activity: "Explore Connaught Place",
              description: "Shop and enjoy street food at this circular commercial hub",
              location: "Connaught Place",
              estimatedCost: "₹800"
            }
          ]
        }
      ],
      tips: [
        "Use Delhi Metro for efficient transportation",
        "Carry water and stay hydrated",
        "Bargain when shopping in local markets",
        "Try local street food but choose busy stalls",
        "Keep your belongings secure in crowded areas"
      ]
    };

    console.log('Mock AI trip plan generated successfully');

    // Return formatted response
    return NextResponse.json({
      success: true,
      tripPlan: mockTripPlan,
      timestamp: new Date().toISOString(),
      source: 'mock-ai-demo'
    });

  } catch (error: any) {
    console.error('Mock AI Error:', error);
    
    return NextResponse.json(
      {
        error: 'Mock AI service error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// Enable CORS for frontend
export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}