import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  let prompt: string = '';
  
  try {
    const requestBody = await request.json();
    prompt = requestBody.prompt;

    // Validate input
    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Invalid prompt. Please provide a valid travel query.' },
        { status: 400 }
      );
    }

    // Create structured prompt for Ollama Llama2
    const structuredPrompt = `You are a travel planning assistant. Create a travel itinerary in JSON format.

User request: ${prompt}

Respond with ONLY a JSON object in this exact format (no other text):

{
  "title": "Trip from [origin] to [destination]",
  "description": "A wonderful [duration] trip covering the best attractions and experiences",
  "destination": "[destination city/region]",
  "from": "[starting location]", 
  "duration": "[number] days",
  "estimatedBudget": "₹[amount]",
  "bestFor": "Solo/Couple/Family/Friends",
  "season": "October-March",
  "itinerary": [
    {
      "day": 1,
      "title": "Day 1 - [theme]",
      "description": "Brief day description",
      "activities": [
        {
          "time": "09:00 AM",
          "activity": "Visit [attraction name]",
          "description": "Activity details",
          "location": "[specific location]",
          "estimatedCost": "₹[amount]"
        }
      ]
    }
  ],
  "tips": ["Keep documents handy", "Book tickets in advance", "Try local cuisine"]
}`;

    console.log('Calling Ollama API at localhost:11434...');

    // Call Ollama API
    const response = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama2',
        prompt: structuredPrompt,
        stream: false, // Get complete response at once
        options: {
          temperature: 0.7,
          top_p: 0.9,
          max_tokens: 3000
        }
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Ollama API error:', response.status, response.statusText);
      console.error('Error body:', errorText);
      
      if (response.status === 404) {
        return NextResponse.json(
          {
            error: 'Ollama model not found. Please ensure Llama2 is installed.',
            details: 'Run: ollama run llama2',
          },
          { status: 503 }
        );
      }
      
      return NextResponse.json(
        {
          error: 'Failed to connect to Ollama. Please ensure Ollama is running.',
          details: `Ollama API error: ${response.statusText}`,
        },
        { status: 503 }
      );
    }

    const data = await response.json();
    const aiText = data?.response;

    if (!aiText || typeof aiText !== 'string') {
      return NextResponse.json(
        { error: 'No response text from Ollama API' },
        { status: 500 }
      );
    }

    console.log('Raw Ollama response:', aiText);

    // Parse JSON response
    let tripPlan: any;
    try {
      // Clean the response - remove any markdown formatting
      let cleanJson = aiText.trim();
      cleanJson = cleanJson.replace(/```json\s*/g, '').replace(/```\s*/g, '');
      
      // Find JSON object in the response
      const jsonStart = cleanJson.indexOf('{');
      const jsonEnd = cleanJson.lastIndexOf('}');
      
      if (jsonStart === -1 || jsonEnd === -1 || jsonEnd <= jsonStart) {
        // If no valid JSON found, create a fallback response
        console.log('No JSON found in Llama2 response, creating fallback...');
        tripPlan = {
          title: `Trip Plan from ${prompt.substring(0, 50)}...`,
          description: "Generated by Ollama Llama2. This is a basic response - the model may need fine-tuning for better JSON output.",
          destination: "Destination from prompt",
          from: "Starting location", 
          duration: "Multiple days",
          estimatedBudget: "₹15,000 - ₹25,000",
          bestFor: "All travelers",
          season: "October-March",
          itinerary: [
            {
              day: 1,
              title: "Day 1 - Exploration",
              description: "Start your journey",
              activities: [
                {
                  time: "09:00 AM",
                  activity: "Begin your travel adventure",
                  description: aiText.substring(0, 200) + "...",
                  location: "As per your request",
                  estimatedCost: "₹500"
                }
              ]
            }
          ],
          tips: ["Carry water", "Book accommodations in advance", "Try local food"]
        };
      } else {
        const jsonString = cleanJson.slice(jsonStart, jsonEnd + 1);
        tripPlan = JSON.parse(jsonString);
      }
      
    } catch (parseError) {
      console.error('JSON parsing error:', parseError);
      console.error('Raw response:', aiText);
      
      // Create a fallback response even when parsing fails
      tripPlan = {
        title: "Ollama Llama2 Travel Response",
        description: "The AI generated a response but it wasn't in the expected JSON format. Raw response included below.",
        destination: "Various locations",
        from: "Your location", 
        duration: "As requested",
        estimatedBudget: "Budget varies",
        bestFor: "All travelers",
        season: "Year-round",
        itinerary: [
          {
            day: 1,
            title: "AI Response",
            description: "Raw Llama2 output",
            activities: [
              {
                time: "Full Day",
                activity: "AI Generated Content",
                description: aiText.length > 300 ? aiText.substring(0, 300) + "..." : aiText,
                location: "Various",
                estimatedCost: "₹0"
              }
            ]
          }
        ],
        tips: ["This is raw AI output", "Consider refining the prompt", "Ollama is working but needs better formatting"]
      };
    }

    // Validate the structure
    if (!tripPlan.title || !tripPlan.itinerary) {
      return NextResponse.json(
        {
          error: 'Invalid trip plan structure from AI',
          details: 'Missing required fields: title or itinerary'
        },
        { status: 500 }
      );
    }

    console.log('Successfully generated trip plan via Ollama');

    // Return formatted response
    return NextResponse.json({
      success: true,
      tripPlan: tripPlan,
      timestamp: new Date().toISOString(),
      source: 'ollama-llama2'
    });

  } catch (error: any) {
    console.error('Ollama Trip Planning Error:', error);
    
    // Check if it's a connection error
    if (error.code === 'ECONNREFUSED' || error.message?.includes('ECONNREFUSED')) {
      return NextResponse.json(
        {
          error: 'Cannot connect to Ollama. Please ensure Ollama is running.',
          details: 'Start Ollama and run: ollama run llama2'
        },
        { status: 503 }
      );
    }
    
    return NextResponse.json(
      {
        error: 'Failed to generate trip plan via Ollama',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// Enable CORS for frontend
export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}