const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Clear existing data
  await prisma.route.deleteMany()
  await prisma.transportMode.deleteMany()

  // Create Transport Modes
  const bus = await prisma.transportMode.create({
    data: {
      name: 'Bus',
      description: 'Comfortable bus services for intercity travel',
      icon: '🚌',
    },
  })

  const train = await prisma.transportMode.create({
    data: {
      name: 'Train',
      description: 'Fast and reliable train services',
      icon: '🚆',
    },
  })

  const flight = await prisma.transportMode.create({
    data: {
      name: 'Flight',
      description: 'Quick air travel between cities',
      icon: '✈️',
    },
  })

  const car = await prisma.transportMode.create({
    data: {
      name: 'Car',
      description: 'Private car rental and ride-sharing',
      icon: '🚗',
    },
  })

  console.log('✅ Transport modes created')

  // Create Routes
  const routes = [
    // Kerala Routes
    {
      source: 'Kochi',
      destination: 'Trivandrum',
      mode: 'Bus',
      modeId: bus.id,
      distance: '210 km',
      duration: '6h 30m',
      price: 450,
      operatorName: 'KSRTC',
      departureTime: '06:00 AM',
      arrivalTime: '12:30 PM',
      frequency: 'Daily',
      amenities: JSON.stringify(['AC', 'WiFi', 'USB Charging']),
      available: true,
    },
    {
      source: 'Kochi',
      destination: 'Trivandrum',
      mode: 'Train',
      modeId: train.id,
      distance: '220 km',
      duration: '4h 15m',
      price: 280,
      operatorName: 'Indian Railways',
      departureTime: '07:30 AM',
      arrivalTime: '11:45 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['AC', 'Pantry', 'Charging Points']),
      available: true,
    },
    {
      source: 'Kochi',
      destination: 'Trivandrum',
      mode: 'Flight',
      modeId: flight.id,
      distance: '180 km',
      duration: '1h',
      price: 3500,
      operatorName: 'IndiGo',
      departureTime: '09:15 AM',
      arrivalTime: '10:15 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['In-flight Service', 'Baggage Allowance']),
      available: true,
    },
    {
      source: 'Kollam',
      destination: 'Goa',
      mode: 'Bus',
      modeId: bus.id,
      distance: '680 km',
      duration: '14h',
      price: 1200,
      operatorName: 'Karnataka SRTC',
      departureTime: '08:00 PM',
      arrivalTime: '10:00 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Sleeper', 'AC', 'Blanket']),
      available: true,
    },
    {
      source: 'Kollam',
      destination: 'Goa',
      mode: 'Train',
      modeId: train.id,
      distance: '700 km',
      duration: '12h 30m',
      price: 850,
      operatorName: 'Indian Railways',
      departureTime: '09:30 PM',
      arrivalTime: '10:00 AM',
      frequency: 'Tue, Thu, Sat',
      amenities: JSON.stringify(['AC', 'Berth', 'Food Available']),
      available: true,
    },
    {
      source: 'Kollam',
      destination: 'Goa',
      mode: 'Flight',
      modeId: flight.id,
      distance: '650 km',
      duration: '1h 30m',
      price: 4800,
      operatorName: 'Air India',
      departureTime: '11:45 AM',
      arrivalTime: '01:15 PM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Meals', 'Entertainment', '20kg Baggage']),
      available: true,
    },
    // More Kerala Routes
    {
      source: 'Kozhikode',
      destination: 'Bangalore',
      mode: 'Bus',
      modeId: bus.id,
      distance: '275 km',
      duration: '7h',
      price: 650,
      operatorName: 'VRL Travels',
      departureTime: '10:00 PM',
      arrivalTime: '05:00 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Volvo', 'AC', 'Water Bottle']),
      available: true,
    },
    {
      source: 'Kozhikode',
      destination: 'Bangalore',
      mode: 'Train',
      modeId: train.id,
      distance: '295 km',
      duration: '6h 30m',
      price: 380,
      operatorName: 'Indian Railways',
      departureTime: '11:30 PM',
      arrivalTime: '06:00 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['AC', 'Sleeper', 'Pantry']),
      available: true,
    },
    {
      source: 'Kozhikode',
      destination: 'Bangalore',
      mode: 'Flight',
      modeId: flight.id,
      distance: '260 km',
      duration: '1h',
      price: 3200,
      operatorName: 'SpiceJet',
      departureTime: '06:30 AM',
      arrivalTime: '07:30 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Snacks', '15kg Baggage']),
      available: true,
    },
    {
      source: 'Thrissur',
      destination: 'Chennai',
      mode: 'Bus',
      modeId: bus.id,
      distance: '480 km',
      duration: '10h',
      price: 900,
      operatorName: 'SRS Travels',
      departureTime: '09:00 PM',
      arrivalTime: '07:00 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Sleeper', 'AC', 'Charging']),
      available: true,
    },
    {
      source: 'Thrissur',
      destination: 'Chennai',
      mode: 'Train',
      modeId: train.id,
      distance: '500 km',
      duration: '8h 30m',
      price: 550,
      operatorName: 'Indian Railways',
      departureTime: '10:30 PM',
      arrivalTime: '07:00 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['AC', '2-tier', 'Food']),
      available: true,
    },
    {
      source: 'Trivandrum',
      destination: 'Mumbai',
      mode: 'Flight',
      modeId: flight.id,
      distance: '1150 km',
      duration: '2h',
      price: 5500,
      operatorName: 'IndiGo',
      departureTime: '08:15 AM',
      arrivalTime: '10:15 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Meals', 'Entertainment', '25kg Baggage']),
      available: true,
    },
    {
      source: 'Kochi',
      destination: 'Delhi',
      mode: 'Flight',
      modeId: flight.id,
      distance: '2140 km',
      duration: '3h 15m',
      price: 6800,
      operatorName: 'Air India',
      departureTime: '06:00 AM',
      arrivalTime: '09:15 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['Premium Meals', 'WiFi', '30kg Baggage']),
      available: true,
    },
    {
      source: 'Kannur',
      destination: 'Mangalore',
      mode: 'Bus',
      modeId: bus.id,
      distance: '95 km',
      duration: '2h 30m',
      price: 180,
      operatorName: 'KSRTC',
      departureTime: '07:00 AM',
      arrivalTime: '09:30 AM',
      frequency: 'Hourly',
      amenities: JSON.stringify(['Non-AC', 'Regular Service']),
      available: true,
    },
    {
      source: 'Kannur',
      destination: 'Mangalore',
      mode: 'Train',
      modeId: train.id,
      distance: '110 km',
      duration: '2h',
      price: 95,
      operatorName: 'Indian Railways',
      departureTime: '08:15 AM',
      arrivalTime: '10:15 AM',
      frequency: 'Daily',
      amenities: JSON.stringify(['General', 'Unreserved']),
      available: true,
    },
    {
      source: 'Alappuzha',
      destination: 'Kottayam',
      mode: 'Bus',
      modeId: bus.id,
      distance: '32 km',
      duration: '1h',
      price: 50,
      operatorName: 'KSRTC',
      departureTime: '06:30 AM',
      arrivalTime: '07:30 AM',
      frequency: 'Every 15 mins',
      amenities: JSON.stringify(['Regular Service']),
      available: true,
    },
    {
      source: 'Mumbai',
      destination: 'Pune',
      mode: 'Bus',
      modeId: bus.id,
      distance: '150 km',
      duration: '3h 30m',
      price: 350,
      operatorName: 'Shivneri',
      departureTime: '06:00 AM',
      arrivalTime: '09:30 AM',
      frequency: 'Every 30 mins',
      amenities: JSON.stringify(['AC', 'WiFi', 'USB']),
      available: true,
    },
    {
      source: 'Mumbai',
      destination: 'Pune',
      mode: 'Train',
      modeId: train.id,
      distance: '145 km',
      duration: '2h 30m',
      price: 180,
      operatorName: 'Indian Railways',
      departureTime: '07:00 AM',
      arrivalTime: '09:30 AM',
      frequency: 'Hourly',
      amenities: JSON.stringify(['AC Chair Car']),
      available: true,
    },
    {
      source: 'Bangalore',
      destination: 'Mysore',
      mode: 'Bus',
      modeId: bus.id,
      distance: '145 km',
      duration: '3h',
      price: 280,
      operatorName: 'KSRTC',
      departureTime: '07:30 AM',
      arrivalTime: '10:30 AM',
      frequency: 'Every 30 mins',
      amenities: JSON.stringify(['Volvo', 'AC']),
      available: true,
    },
    {
      source: 'Bangalore',
      destination: 'Mysore',
      mode: 'Car',
      modeId: car.id,
      distance: '145 km',
      duration: '2h 45m',
      price: 1200,
      operatorName: 'Ola Outstation',
      departureTime: 'On Demand',
      arrivalTime: '-',
      frequency: '24/7',
      amenities: JSON.stringify(['Private', 'AC', 'Driver']),
      available: true,
    },
  ]

  for (const route of routes) {
    await prisma.route.create({ data: route })
  }

  console.log(`✅ Created ${routes.length} routes`)
  console.log('🎉 Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
