// Static routes database for WayWise Travel Assistant
// This replaces all external API calls with local data

export interface Route {
  id: string;
  from: string;
  to: string;
  mode: string;
  duration: string;
  cost: string;
  rating: number;
  description: string;
  tags: string[];
  avg_cost: string;
  country: string;
  distance?: string;
  departure_time?: string;
  arrival_time?: string;
  operator?: string;
  amenities?: string[];
}

export const routesDatabase: Route[] = [
  {
    id: "KOC-DXB-FL-001",
    from: "Kochi",
    to: "Dubai",
    mode: "Flight",
    duration: "4h 20m",
    cost: "₹18,000",
    rating: 4.9,
    description: "Luxury shopping, ultramodern architecture",
    tags: ["Luxury", "Shopping", "Modern"],
    avg_cost: "₹₹₹",
    country: "UAE",
    distance: "3,025 km",
    departure_time: "06:00 AM",
    arrival_time: "08:20 AM",
    operator: "Emirates",
    amenities: ["Meal", "WiFi", "Entertainment"]
  },
  {
    id: "KOC-MLE-FL-001",
    from: "Kochi",
    to: "Maldives",
    mode: "Flight",
    duration: "1h 30m",
    cost: "₹12,000",
    rating: 5.0,
    description: "Tropical paradise with crystal clear waters",
    tags: ["Beach", "Luxury", "Honeymoon"],
    avg_cost: "₹₹₹₹",
    country: "Maldives",
    distance: "760 km",
    departure_time: "09:30 AM",
    arrival_time: "10:00 AM",
    operator: "IndiGo",
    amenities: ["Snacks", "Entertainment"]
  },
  {
    id: "KOC-DPS-FL-001",
    from: "Kochi",
    to: "Bali",
    mode: "Flight",
    duration: "7h 10m",
    cost: "₹22,000",
    rating: 4.8,
    description: "Island of gods with temples and beaches",
    tags: ["Beach", "Culture", "Temples"],
    avg_cost: "₹₹",
    country: "Indonesia",
    distance: "4,200 km",
    departure_time: "10:00 AM",
    arrival_time: "08:10 PM",
    operator: "Air India",
    amenities: ["Meal", "WiFi", "Entertainment"]
  },
  {
    id: "KOC-ZRH-FL-001",
    from: "Kochi",
    to: "Switzerland",
    mode: "Flight",
    duration: "11h 30m",
    cost: "₹65,000",
    rating: 4.9,
    description: "Snowy mountains and scenic beauty",
    tags: ["Luxury", "Nature", "Adventure"],
    avg_cost: "₹₹₹₹",
    country: "Switzerland",
    distance: "6,850 km",
    departure_time: "02:00 PM",
    arrival_time: "07:30 PM",
    operator: "Swiss Air",
    amenities: ["Meal", "WiFi", "Entertainment", "Lounge"]
  },
  {
    id: "KOC-SIN-FL-001",
    from: "Kochi",
    to: "Singapore",
    mode: "Flight",
    duration: "4h 45m",
    cost: "₹16,500",
    rating: 4.8,
    description: "Garden city with modern attractions",
    tags: ["Urban", "Modern", "Family"],
    avg_cost: "₹₹₹",
    country: "Singapore",
    distance: "2,800 km",
    departure_time: "11:00 PM",
    arrival_time: "06:45 AM",
    operator: "Singapore Airlines",
    amenities: ["Meal", "WiFi", "Entertainment"]
  },
  {
    id: "KOC-BKK-FL-001",
    from: "Kochi",
    to: "Thailand",
    mode: "Flight",
    duration: "3h 50m",
    cost: "₹14,000",
    rating: 4.7,
    description: "Beaches, temples and vibrant nightlife",
    tags: ["Beach", "Culture", "Nightlife"],
    avg_cost: "₹₹",
    country: "Thailand",
    distance: "2,400 km",
    departure_time: "07:30 AM",
    arrival_time: "12:20 PM",
    operator: "Thai Airways",
    amenities: ["Meal", "Entertainment"]
  },
  {
    id: "KOC-DEL-FL-001",
    from: "Kochi",
    to: "Delhi",
    mode: "Flight",
    duration: "3h 00m",
    cost: "₹6,800",
    rating: 4.5,
    description: "Capital city with rich history and monuments",
    tags: ["Heritage", "Culture", "History"],
    avg_cost: "₹₹",
    country: "India",
    distance: "2,350 km",
    departure_time: "06:00 AM",
    arrival_time: "09:00 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-BOM-FL-001",
    from: "Kochi",
    to: "Mumbai",
    mode: "Flight",
    duration: "2h 15m",
    cost: "₹5,500",
    rating: 4.6,
    description: "City of dreams and Bollywood",
    tags: ["Urban", "Entertainment", "Beach"],
    avg_cost: "₹₹₹",
    country: "India",
    distance: "1,150 km",
    departure_time: "08:30 AM",
    arrival_time: "10:45 AM",
    operator: "Air India",
    amenities: ["Snacks", "WiFi"]
  },
  {
    id: "KOC-JAI-FL-001",
    from: "Kochi",
    to: "Jaipur",
    mode: "Flight",
    duration: "3h 15m",
    cost: "₹6,500",
    rating: 4.6,
    description: "Pink city with royal palaces and forts",
    tags: ["Heritage", "Culture", "History"],
    avg_cost: "₹",
    country: "India",
    distance: "2,100 km",
    departure_time: "07:00 AM",
    arrival_time: "10:15 AM",
    operator: "SpiceJet",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-MAA-TR-001",
    from: "Kochi",
    to: "Chennai",
    mode: "Train",
    duration: "13h 00m",
    cost: "₹900",
    rating: 4.2,
    description: "Cultural hub of Tamil Nadu",
    tags: ["Culture", "Food", "Temple"],
    avg_cost: "₹",
    country: "India",
    distance: "685 km",
    departure_time: "06:00 PM",
    arrival_time: "07:00 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "KOC-MAA-FL-001",
    from: "Kochi",
    to: "Chennai",
    mode: "Flight",
    duration: "1h 10m",
    cost: "₹4,200",
    rating: 4.4,
    description: "Quick flight to Tamil Nadu's capital",
    tags: ["Culture", "Food", "Temple"],
    avg_cost: "₹",
    country: "India",
    distance: "685 km",
    departure_time: "09:00 AM",
    arrival_time: "10:10 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-CCU-FL-001",
    from: "Kochi",
    to: "Kolkata",
    mode: "Flight",
    duration: "2h 50m",
    cost: "₹5,800",
    rating: 4.4,
    description: "Historic city with colonial architecture",
    tags: ["Culture", "Heritage"],
    avg_cost: "₹₹",
    country: "India",
    distance: "2,050 km",
    departure_time: "10:30 AM",
    arrival_time: "01:20 PM",
    operator: "IndiGo",
    amenities: ["Snacks", "WiFi"]
  },
  {
    id: "KOC-GOI-BUS-001",
    from: "Kochi",
    to: "Goa",
    mode: "Bus",
    duration: "15h 40m",
    cost: "₹1,200",
    rating: 4.7,
    description: "Party capital with beaches and nightlife",
    tags: ["Beach", "Nightlife", "Relaxation"],
    avg_cost: "₹₹",
    country: "India",
    distance: "920 km",
    departure_time: "06:00 PM",
    arrival_time: "09:40 AM",
    operator: "KSRTC Sleeper",
    amenities: ["AC", "Sleeper", "Charging Port"]
  },
  {
    id: "KOC-GOI-FL-001",
    from: "Kochi",
    to: "Goa",
    mode: "Flight",
    duration: "1h 20m",
    cost: "₹4,800",
    rating: 4.7,
    description: "Quick hop to beach paradise",
    tags: ["Beach", "Nightlife", "Relaxation"],
    avg_cost: "₹₹",
    country: "India",
    distance: "920 km",
    departure_time: "11:00 AM",
    arrival_time: "12:20 PM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-BLR-BUS-001",
    from: "Kochi",
    to: "Bangalore",
    mode: "Bus",
    duration: "11h 30m",
    cost: "₹800",
    rating: 4.3,
    description: "IT hub and garden city",
    tags: ["Urban", "Tech", "Food"],
    avg_cost: "₹₹",
    country: "India",
    distance: "540 km",
    departure_time: "10:00 PM",
    arrival_time: "09:30 AM",
    operator: "VRL Travels",
    amenities: ["AC", "Sleeper", "WiFi"]
  },
  {
    id: "KOC-BLR-FL-001",
    from: "Kochi",
    to: "Bangalore",
    mode: "Flight",
    duration: "1h 05m",
    cost: "₹3,500",
    rating: 4.5,
    description: "Fast route to Silicon Valley of India",
    tags: ["Urban", "Tech", "Food"],
    avg_cost: "₹₹",
    country: "India",
    distance: "540 km",
    departure_time: "07:00 AM",
    arrival_time: "08:05 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-HYD-FL-001",
    from: "Kochi",
    to: "Hyderabad",
    mode: "Flight",
    duration: "1h 40m",
    cost: "₹5,200",
    rating: 4.4,
    description: "City of pearls and biryani",
    tags: ["Culture", "Food", "Heritage"],
    avg_cost: "₹₹",
    country: "India",
    distance: "1,050 km",
    departure_time: "12:00 PM",
    arrival_time: "01:40 PM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "KOC-PNQ-FL-001",
    from: "Kochi",
    to: "Pune",
    mode: "Flight",
    duration: "2h 00m",
    cost: "₹5,600",
    rating: 4.3,
    description: "Cultural capital of Maharashtra",
    tags: ["Culture", "Education", "Heritage"],
    avg_cost: "₹₹",
    country: "India",
    distance: "1,050 km",
    departure_time: "02:00 PM",
    arrival_time: "04:00 PM",
    operator: "Air India",
    amenities: ["Snacks", "WiFi"]
  },
  {
    id: "KOC-AMD-FL-001",
    from: "Kochi",
    to: "Ahmedabad",
    mode: "Flight",
    duration: "2h 30m",
    cost: "₹6,200",
    rating: 4.2,
    description: "Heritage city of Gujarat",
    tags: ["Heritage", "Culture", "Food"],
    avg_cost: "₹",
    country: "India",
    distance: "1,550 km",
    departure_time: "01:00 PM",
    arrival_time: "03:30 PM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "TRV-KOC-TR-001",
    from: "Thiruvananthapuram",
    to: "Kochi",
    mode: "Train",
    duration: "4h 10m",
    cost: "₹250",
    rating: 4.3,
    description: "Scenic route across Kerala coast",
    tags: ["Local", "Scenic", "Affordable"],
    avg_cost: "₹",
    country: "India",
    distance: "220 km",
    departure_time: "06:00 AM",
    arrival_time: "10:10 AM",
    operator: "Indian Railways",
    amenities: ["Pantry"]
  },
  {
    id: "TRV-DXB-FL-001",
    from: "Thiruvananthapuram",
    to: "Dubai",
    mode: "Flight",
    duration: "4h 30m",
    cost: "₹17,500",
    rating: 4.9,
    description: "Direct flight to luxury destination",
    tags: ["Luxury", "Shopping", "Modern"],
    avg_cost: "₹₹₹",
    country: "UAE",
    distance: "3,100 km",
    departure_time: "05:00 AM",
    arrival_time: "07:30 AM",
    operator: "Emirates",
    amenities: ["Meal", "WiFi", "Entertainment"]
  },
  {
    id: "TRV-MLE-FL-001",
    from: "Thiruvananthapuram",
    to: "Maldives",
    mode: "Flight",
    duration: "1h 15m",
    cost: "₹11,500",
    rating: 5.0,
    description: "Quick escape to island paradise",
    tags: ["Beach", "Luxury", "Honeymoon"],
    avg_cost: "₹₹₹₹",
    country: "Maldives",
    distance: "680 km",
    departure_time: "10:00 AM",
    arrival_time: "10:15 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "TRV-DEL-FL-001",
    from: "Thiruvananthapuram",
    to: "Delhi",
    mode: "Flight",
    duration: "3h 20m",
    cost: "₹7,200",
    rating: 4.5,
    description: "Capital city connection",
    tags: ["Heritage", "Culture", "History"],
    avg_cost: "₹₹",
    country: "India",
    distance: "2,550 km",
    departure_time: "06:30 AM",
    arrival_time: "09:50 AM",
    operator: "Air India",
    amenities: ["Meal"]
  },
  {
    id: "TRV-BOM-FL-001",
    from: "Thiruvananthapuram",
    to: "Mumbai",
    mode: "Flight",
    duration: "2h 20m",
    cost: "₹5,800",
    rating: 4.6,
    description: "Gateway to financial capital",
    tags: ["Urban", "Entertainment", "Beach"],
    avg_cost: "₹₹₹",
    country: "India",
    distance: "1,250 km",
    departure_time: "09:00 AM",
    arrival_time: "11:20 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "TRV-BLR-FL-001",
    from: "Thiruvananthapuram",
    to: "Bangalore",
    mode: "Flight",
    duration: "1h 15m",
    cost: "₹3,800",
    rating: 4.5,
    description: "Quick hop to IT city",
    tags: ["Urban", "Tech", "Food"],
    avg_cost: "₹₹",
    country: "India",
    distance: "570 km",
    departure_time: "07:30 AM",
    arrival_time: "08:45 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "CCJ-KOC-BUS-001",
    from: "Kozhikode",
    to: "Kochi",
    mode: "Bus",
    duration: "5h 00m",
    cost: "₹300",
    rating: 4.1,
    description: "Comfortable road trip across Kerala",
    tags: ["Local", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "190 km",
    departure_time: "08:00 AM",
    arrival_time: "01:00 PM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "CCJ-DXB-FL-001",
    from: "Kozhikode",
    to: "Dubai",
    mode: "Flight",
    duration: "4h 15m",
    cost: "₹17,800",
    rating: 4.9,
    description: "Direct route to UAE",
    tags: ["Luxury", "Shopping", "Modern"],
    avg_cost: "₹₹₹",
    country: "UAE",
    distance: "2,950 km",
    departure_time: "05:30 AM",
    arrival_time: "07:45 AM",
    operator: "Emirates",
    amenities: ["Meal", "WiFi", "Entertainment"]
  },
  {
    id: "CCJ-BLR-FL-001",
    from: "Kozhikode",
    to: "Bangalore",
    mode: "Flight",
    duration: "1h 20m",
    cost: "₹4,200",
    rating: 4.4,
    description: "Fast connection to Bangalore",
    tags: ["Urban", "Tech", "Food"],
    avg_cost: "₹₹",
    country: "India",
    distance: "340 km",
    departure_time: "08:00 AM",
    arrival_time: "09:20 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "CCJ-MAA-FL-001",
    from: "Kozhikode",
    to: "Chennai",
    mode: "Flight",
    duration: "1h 25m",
    cost: "₹4,800",
    rating: 4.3,
    description: "Quick flight to Chennai",
    tags: ["Culture", "Food", "Temple"],
    avg_cost: "₹",
    country: "India",
    distance: "450 km",
    departure_time: "10:00 AM",
    arrival_time: "11:25 AM",
    operator: "Air India",
    amenities: ["Snacks"]
  },
  {
    id: "CCJ-DEL-FL-001",
    from: "Kozhikode",
    to: "Delhi",
    mode: "Flight",
    duration: "3h 30m",
    cost: "₹7,500",
    rating: 4.4,
    description: "Northern capital connection",
    tags: ["Heritage", "Culture", "History"],
    avg_cost: "₹₹",
    country: "India",
    distance: "2,150 km",
    departure_time: "07:00 AM",
    arrival_time: "10:30 AM",
    operator: "IndiGo",
    amenities: ["Meal"]
  },
  {
    id: "CCJ-BOM-FL-001",
    from: "Kozhikode",
    to: "Mumbai",
    mode: "Flight",
    duration: "2h 10m",
    cost: "₹6,200",
    rating: 4.5,
    description: "West coast to financial hub",
    tags: ["Urban", "Entertainment", "Beach"],
    avg_cost: "₹₹₹",
    country: "India",
    distance: "1,050 km",
    departure_time: "09:30 AM",
    arrival_time: "11:40 AM",
    operator: "Air India",
    amenities: ["Snacks", "WiFi"]
  },
  {
    id: "TCR-KOC-BUS-001",
    from: "Thrissur",
    to: "Kochi",
    mode: "Bus",
    duration: "1h 30m",
    cost: "₹150",
    rating: 4.2,
    description: "Short trip to port city",
    tags: ["Local", "Budget", "Quick"],
    avg_cost: "₹",
    country: "India",
    distance: "75 km",
    departure_time: "07:00 AM",
    arrival_time: "08:30 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "TCR-MAA-TR-001",
    from: "Thrissur",
    to: "Chennai",
    mode: "Train",
    duration: "9h 30m",
    cost: "₹700",
    rating: 4.1,
    description: "Scenic train journey",
    tags: ["Culture", "Affordable", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "610 km",
    departure_time: "10:00 PM",
    arrival_time: "07:30 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "TCR-BLR-BUS-001",
    from: "Thrissur",
    to: "Bangalore",
    mode: "Bus",
    duration: "8h 00m",
    cost: "₹650",
    rating: 4.0,
    description: "Overnight bus to IT city",
    tags: ["Budget", "Overnight"],
    avg_cost: "₹₹",
    country: "India",
    distance: "470 km",
    departure_time: "11:00 PM",
    arrival_time: "07:00 AM",
    operator: "SRS Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "TCR-GOI-BUS-001",
    from: "Thrissur",
    to: "Goa",
    mode: "Bus",
    duration: "14h 00m",
    cost: "₹1,100",
    rating: 4.3,
    description: "Road trip to beach destination",
    tags: ["Beach", "Budget", "Adventure"],
    avg_cost: "₹₹",
    country: "India",
    distance: "850 km",
    departure_time: "07:00 PM",
    arrival_time: "09:00 AM",
    operator: "Paulo Travels",
    amenities: ["AC", "Sleeper", "WiFi"]
  },
  {
    id: "TCR-TRV-BUS-001",
    from: "Thrissur",
    to: "Thiruvananthapuram",
    mode: "Bus",
    duration: "5h 30m",
    cost: "₹400",
    rating: 4.1,
    description: "Journey to capital city",
    tags: ["Local", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "295 km",
    departure_time: "08:00 AM",
    arrival_time: "01:30 PM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "ALP-KOC-BUS-001",
    from: "Alappuzha",
    to: "Kochi",
    mode: "Bus",
    duration: "1h 45m",
    cost: "₹120",
    rating: 4.3,
    description: "Backwater to port city",
    tags: ["Local", "Quick", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "60 km",
    departure_time: "06:00 AM",
    arrival_time: "07:45 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "ALP-TRV-TR-001",
    from: "Alappuzha",
    to: "Thiruvananthapuram",
    mode: "Train",
    duration: "2h 30m",
    cost: "₹180",
    rating: 4.2,
    description: "Coastal rail journey",
    tags: ["Local", "Scenic", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "160 km",
    departure_time: "08:00 AM",
    arrival_time: "10:30 AM",
    operator: "Indian Railways",
    amenities: ["Pantry"]
  },
  {
    id: "ALP-MAA-TR-001",
    from: "Alappuzha",
    to: "Chennai",
    mode: "Train",
    duration: "11h 00m",
    cost: "₹750",
    rating: 4.0,
    description: "Long journey to Tamil Nadu",
    tags: ["Culture", "Overnight"],
    avg_cost: "₹",
    country: "India",
    distance: "650 km",
    departure_time: "09:00 PM",
    arrival_time: "08:00 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "ALP-BLR-BUS-001",
    from: "Alappuzha",
    to: "Bangalore",
    mode: "Bus",
    duration: "10h 30m",
    cost: "₹800",
    rating: 4.1,
    description: "Backwaters to tech city",
    tags: ["Urban", "Overnight"],
    avg_cost: "₹₹",
    country: "India",
    distance: "530 km",
    departure_time: "10:00 PM",
    arrival_time: "08:30 AM",
    operator: "VRL Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "ALP-GOI-BUS-001",
    from: "Alappuzha",
    to: "Goa",
    mode: "Bus",
    duration: "16h 00m",
    cost: "₹1,300",
    rating: 4.2,
    description: "Beach to beach journey",
    tags: ["Beach", "Adventure"],
    avg_cost: "₹₹",
    country: "India",
    distance: "900 km",
    departure_time: "06:00 PM",
    arrival_time: "10:00 AM",
    operator: "Kallada Travels",
    amenities: ["AC", "Sleeper", "WiFi"]
  },
  {
    id: "KTM-KOC-BUS-001",
    from: "Kottayam",
    to: "Kochi",
    mode: "Bus",
    duration: "2h 00m",
    cost: "₹180",
    rating: 4.2,
    description: "Hill station to city",
    tags: ["Local", "Quick"],
    avg_cost: "₹",
    country: "India",
    distance: "85 km",
    departure_time: "07:00 AM",
    arrival_time: "09:00 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "KTM-TRV-TR-001",
    from: "Kottayam",
    to: "Thiruvananthapuram",
    mode: "Train",
    duration: "3h 15m",
    cost: "₹220",
    rating: 4.1,
    description: "Central Kerala to capital",
    tags: ["Local", "Affordable"],
    avg_cost: "₹",
    country: "India",
    distance: "165 km",
    departure_time: "09:00 AM",
    arrival_time: "12:15 PM",
    operator: "Indian Railways",
    amenities: ["Pantry"]
  },
  {
    id: "KTM-BLR-BUS-001",
    from: "Kottayam",
    to: "Bangalore",
    mode: "Bus",
    duration: "9h 30m",
    cost: "₹750",
    rating: 4.0,
    description: "Night bus to IT hub",
    tags: ["Urban", "Overnight"],
    avg_cost: "₹₹",
    country: "India",
    distance: "500 km",
    departure_time: "10:00 PM",
    arrival_time: "07:30 AM",
    operator: "KPN Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "KTM-MAA-TR-001",
    from: "Kottayam",
    to: "Chennai",
    mode: "Train",
    duration: "10h 30m",
    cost: "₹720",
    rating: 4.1,
    description: "Train to cultural capital",
    tags: ["Culture", "Overnight"],
    avg_cost: "₹",
    country: "India",
    distance: "630 km",
    departure_time: "09:30 PM",
    arrival_time: "08:00 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "KTM-MNR-BUS-001",
    from: "Kottayam",
    to: "Munnar",
    mode: "Bus",
    duration: "3h 00m",
    cost: "₹200",
    rating: 4.5,
    description: "Journey to tea gardens",
    tags: ["Nature", "Hill Station", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "110 km",
    departure_time: "08:00 AM",
    arrival_time: "11:00 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "PKD-KOC-BUS-001",
    from: "Palakkad",
    to: "Kochi",
    mode: "Bus",
    duration: "3h 30m",
    cost: "₹280",
    rating: 4.0,
    description: "Gateway town to port city",
    tags: ["Local", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "130 km",
    departure_time: "07:00 AM",
    arrival_time: "10:30 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "PKD-CJB-BUS-001",
    from: "Palakkad",
    to: "Coimbatore",
    mode: "Bus",
    duration: "1h 30m",
    cost: "₹100",
    rating: 4.3,
    description: "Quick hop to Tamil Nadu",
    tags: ["Local", "Quick", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "55 km",
    departure_time: "06:00 AM",
    arrival_time: "07:30 AM",
    operator: "KSRTC",
    amenities: ["Non-AC"]
  },
  {
    id: "PKD-BLR-BUS-001",
    from: "Palakkad",
    to: "Bangalore",
    mode: "Bus",
    duration: "7h 00m",
    cost: "₹600",
    rating: 4.2,
    description: "Direct route to IT city",
    tags: ["Urban", "Affordable"],
    avg_cost: "₹₹",
    country: "India",
    distance: "360 km",
    departure_time: "11:00 PM",
    arrival_time: "06:00 AM",
    operator: "Orange Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "PKD-MAA-TR-001",
    from: "Palakkad",
    to: "Chennai",
    mode: "Train",
    duration: "8h 00m",
    cost: "₹650",
    rating: 4.1,
    description: "Train journey to Chennai",
    tags: ["Culture", "Overnight"],
    avg_cost: "₹",
    country: "India",
    distance: "495 km",
    departure_time: "11:00 PM",
    arrival_time: "07:00 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "PKD-TRV-BUS-001",
    from: "Palakkad",
    to: "Thiruvananthapuram",
    mode: "Bus",
    duration: "6h 30m",
    cost: "₹450",
    rating: 4.0,
    description: "Cross-Kerala journey",
    tags: ["Local", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "350 km",
    departure_time: "08:00 AM",
    arrival_time: "02:30 PM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "CNN-KOC-TR-001",
    from: "Kannur",
    to: "Kochi",
    mode: "Train",
    duration: "5h 30m",
    cost: "₹320",
    rating: 4.2,
    description: "Coastal railway journey",
    tags: ["Local", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "260 km",
    departure_time: "07:00 AM",
    arrival_time: "12:30 PM",
    operator: "Indian Railways",
    amenities: ["Pantry"]
  },
  {
    id: "CNN-BLR-FL-001",
    from: "Kannur",
    to: "Bangalore",
    mode: "Flight",
    duration: "1h 10m",
    cost: "₹4,500",
    rating: 4.4,
    description: "Quick flight to tech city",
    tags: ["Urban", "Quick"],
    avg_cost: "₹₹",
    country: "India",
    distance: "310 km",
    departure_time: "09:00 AM",
    arrival_time: "10:10 AM",
    operator: "IndiGo",
    amenities: ["Snacks"]
  },
  {
    id: "CNN-GOI-TR-001",
    from: "Kannur",
    to: "Goa",
    mode: "Train",
    duration: "10h 30m",
    cost: "₹900",
    rating: 4.3,
    description: "Konkan railway route",
    tags: ["Beach", "Scenic", "Adventure"],
    avg_cost: "₹₹",
    country: "India",
    distance: "590 km",
    departure_time: "09:00 PM",
    arrival_time: "07:30 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "CNN-BOM-TR-001",
    from: "Kannur",
    to: "Mumbai",
    mode: "Train",
    duration: "18h 00m",
    cost: "₹1,200",
    rating: 4.1,
    description: "Long coastal journey",
    tags: ["Urban", "Overnight"],
    avg_cost: "₹₹₹",
    country: "India",
    distance: "1,180 km",
    departure_time: "03:00 PM",
    arrival_time: "09:00 AM",
    operator: "Indian Railways",
    amenities: ["AC", "Pantry"]
  },
  {
    id: "CNN-DXB-FL-001",
    from: "Kannur",
    to: "Dubai",
    mode: "Flight",
    duration: "4h 30m",
    cost: "₹18,200",
    rating: 4.8,
    description: "Direct international flight",
    tags: ["Luxury", "Shopping", "Modern"],
    avg_cost: "₹₹₹",
    country: "UAE",
    distance: "2,900 km",
    departure_time: "06:00 AM",
    arrival_time: "08:30 AM",
    operator: "Air Arabia",
    amenities: ["Meal", "Entertainment"]
  },
  {
    id: "QLN-KOC-TR-001",
    from: "Kollam",
    to: "Kochi",
    mode: "Train",
    duration: "3h 00m",
    cost: "₹200",
    rating: 4.2,
    description: "Coastal city connection",
    tags: ["Local", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "150 km",
    departure_time: "08:00 AM",
    arrival_time: "11:00 AM",
    operator: "Indian Railways",
    amenities: ["Pantry"]
  },
  {
    id: "QLN-TRV-BUS-001",
    from: "Kollam",
    to: "Thiruvananthapuram",
    mode: "Bus",
    duration: "1h 30m",
    cost: "₹100",
    rating: 4.3,
    description: "Quick trip to capital",
    tags: ["Local", "Quick", "Budget"],
    avg_cost: "₹",
    country: "India",
    distance: "70 km",
    departure_time: "07:00 AM",
    arrival_time: "08:30 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "QLN-BLR-BUS-001",
    from: "Kollam",
    to: "Bangalore",
    mode: "Bus",
    duration: "11h 00m",
    cost: "₹850",
    rating: 4.0,
    description: "Overnight to IT city",
    tags: ["Urban", "Overnight"],
    avg_cost: "₹₹",
    country: "India",
    distance: "600 km",
    departure_time: "09:00 PM",
    arrival_time: "08:00 AM",
    operator: "Sharma Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "QLN-MAA-TR-001",
    from: "Kollam",
    to: "Chennai",
    mode: "Train",
    duration: "12h 30m",
    cost: "₹800",
    rating: 4.1,
    description: "Long train journey",
    tags: ["Culture", "Overnight"],
    avg_cost: "₹",
    country: "India",
    distance: "730 km",
    departure_time: "08:00 PM",
    arrival_time: "08:30 AM",
    operator: "Indian Railways",
    amenities: ["Sleeper", "Pantry"]
  },
  {
    id: "QLN-GOI-BUS-001",
    from: "Kollam",
    to: "Goa",
    mode: "Bus",
    duration: "16h 30m",
    cost: "₹1,250",
    rating: 4.2,
    description: "Coastal road adventure",
    tags: ["Beach", "Adventure"],
    avg_cost: "₹₹",
    country: "India",
    distance: "950 km",
    departure_time: "05:00 PM",
    arrival_time: "09:30 AM",
    operator: "Neeta Travels",
    amenities: ["AC", "Sleeper", "WiFi"]
  },
  {
    id: "IDK-KOC-BUS-001",
    from: "Idukki",
    to: "Kochi",
    mode: "Bus",
    duration: "4h 00m",
    cost: "₹280",
    rating: 4.4,
    description: "Hill station to city descent",
    tags: ["Nature", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "140 km",
    departure_time: "07:00 AM",
    arrival_time: "11:00 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "IDK-MNR-BUS-001",
    from: "Idukki",
    to: "Munnar",
    mode: "Bus",
    duration: "2h 00m",
    cost: "₹150",
    rating: 4.6,
    description: "Mountain roads journey",
    tags: ["Nature", "Hill Station", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "55 km",
    departure_time: "09:00 AM",
    arrival_time: "11:00 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "IDK-TKD-BUS-001",
    from: "Idukki",
    to: "Thekkady",
    mode: "Bus",
    duration: "1h 30m",
    cost: "₹120",
    rating: 4.5,
    description: "Wildlife sanctuary visit",
    tags: ["Nature", "Wildlife", "Adventure"],
    avg_cost: "₹",
    country: "India",
    distance: "40 km",
    departure_time: "08:00 AM",
    arrival_time: "09:30 AM",
    operator: "KSRTC",
    amenities: ["Non-AC"]
  },
  {
    id: "IDK-BLR-BUS-001",
    from: "Idukki",
    to: "Bangalore",
    mode: "Bus",
    duration: "7h 30m",
    cost: "₹700",
    rating: 4.2,
    description: "Scenic mountain route",
    tags: ["Urban", "Scenic"],
    avg_cost: "₹₹",
    country: "India",
    distance: "420 km",
    departure_time: "11:00 PM",
    arrival_time: "06:30 AM",
    operator: "Parveen Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "IDK-TRV-BUS-001",
    from: "Idukki",
    to: "Thiruvananthapuram",
    mode: "Bus",
    duration: "6h 00m",
    cost: "₹500",
    rating: 4.1,
    description: "Hills to coast journey",
    tags: ["Local", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "290 km",
    departure_time: "08:00 AM",
    arrival_time: "02:00 PM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "WYD-KOC-BUS-001",
    from: "Wayanad",
    to: "Kochi",
    mode: "Bus",
    duration: "5h 30m",
    cost: "₹350",
    rating: 4.3,
    description: "Forest trails to city",
    tags: ["Nature", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "270 km",
    departure_time: "07:00 AM",
    arrival_time: "12:30 PM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "WYD-BLR-BUS-001",
    from: "Wayanad",
    to: "Bangalore",
    mode: "Bus",
    duration: "5h 00m",
    cost: "₹550",
    rating: 4.4,
    description: "Shortest route to Bangalore",
    tags: ["Urban", "Quick"],
    avg_cost: "₹₹",
    country: "India",
    distance: "270 km",
    departure_time: "11:00 PM",
    arrival_time: "04:00 AM",
    operator: "SRS Travels",
    amenities: ["AC", "Sleeper"]
  },
  {
    id: "WYD-MYS-BUS-001",
    from: "Wayanad",
    to: "Mysore",
    mode: "Bus",
    duration: "3h 30m",
    cost: "₹300",
    rating: 4.3,
    description: "Hill station to heritage city",
    tags: ["Heritage", "Culture"],
    avg_cost: "₹",
    country: "India",
    distance: "120 km",
    departure_time: "08:00 AM",
    arrival_time: "11:30 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "WYD-CCJ-BUS-001",
    from: "Wayanad",
    to: "Kozhikode",
    mode: "Bus",
    duration: "3h 00m",
    cost: "₹200",
    rating: 4.2,
    description: "Ghat road descent",
    tags: ["Local", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "100 km",
    departure_time: "07:00 AM",
    arrival_time: "10:00 AM",
    operator: "KSRTC",
    amenities: ["AC"]
  },
  {
    id: "WYD-OTY-BUS-001",
    from: "Wayanad",
    to: "Ooty",
    mode: "Bus",
    duration: "4h 00m",
    cost: "₹350",
    rating: 4.5,
    description: "Hill station to hill station",
    tags: ["Nature", "Hill Station", "Scenic"],
    avg_cost: "₹",
    country: "India",
    distance: "140 km",
    departure_time: "08:00 AM",
    arrival_time: "12:00 PM",
    operator: "TNSTC",
    amenities: ["AC"]
  }
];

// Helper function to search routes
export function searchRoutes(from?: string, to?: string, mode?: string) {
  let results = routesDatabase;

  if (from) {
    results = results.filter(route => 
      route.from.toLowerCase().includes(from.toLowerCase())
    );
  }

  if (to) {
    results = results.filter(route => 
      route.to.toLowerCase().includes(to.toLowerCase())
    );
  }

  if (mode) {
    results = results.filter(route => 
      route.mode.toLowerCase() === mode.toLowerCase()
    );
  }

  return results;
}

// Get all unique cities
export function getAllCities() {
  const cities = new Set<string>();
  routesDatabase.forEach(route => {
    cities.add(route.from);
    cities.add(route.to);
  });
  return Array.from(cities).sort();
}

// Get all modes of transport
export function getAllModes() {
  const modes = new Set<string>();
  routesDatabase.forEach(route => {
    modes.add(route.mode);
  });
  return Array.from(modes).sort();
}
